FROM golang:1.9-alpine AS builder
WORKDIR /go/src/github.com/caarlos0/app
ADD . .
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
RUN go build --ldflags "-s -w" -o app .

FROM scratch
EXPOSE 8080
WORKDIR /root
COPY --from=builder /go/src/github.com/caarlos0/app .
ENTRYPOINT ["./app"]
